copy over 1es files

diff --git a/.github/workflows/reusable-test.yml b/.github/workflows/reusable-test.yml
--- a/.github/workflows/reusable-test.yml
+++ b/.github/workflows/reusable-test.yml
@@ -63,13 +63,13 @@ permissions:
 
 jobs:
   run_test:
-    # Due to app-verifier, unit tests take a lot longer to execute. Increase the timeout to 90 minutes.
-    timeout-minutes: 90
+    # VM-backed driver tests can include VM recovery and dump collection.
+    timeout-minutes: 150
 
     strategy:
       matrix:
         configurations: ${{ fromJSON(inputs.configurations) }}
-    runs-on: ${{inputs.environment}}
+    runs-on: ${{ fromJSON(format(inputs.environment, strategy.job-index)) }}
     env:
       # Configuration type to build.
       SOURCE_ROOT: ${{github.workspace}}
@@ -101,9 +101,14 @@ jobs:
     - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
       # Check out source code if code coverage is being gathered or if crash dumps
       # (which require ProcDump downloaded via the repo scripts) are being gathered.
-      if: ((inputs.code_coverage == true) || (inputs.gather_dumps == true)) && (steps.skip_check.outputs.should_skip != 'true')
+      if: ((inputs.code_coverage == true) || (inputs.gather_dumps == true)) && !contains(inputs.environment, '1ES') && (steps.skip_check.outputs.should_skip != 'true')
       with:
         submodules: 'recursive'
+        ref: ${{ github.event.workflow_run.head_branch }}
+
+    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
+      if: contains(inputs.environment, '1ES') && (steps.skip_check.outputs.should_skip != 'true')
+      with:
         ref: ${{ github.event.workflow_run.head_branch }}
 
     - name: Install ProcDump
@@ -143,7 +148,7 @@ jobs:
 
     - name: Set up OpenCppCoverage and add to PATH
       id: set_up_opencppcoverage
-      if: (inputs.code_coverage == true) && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022') && (steps.skip_check.outputs.should_skip != 'true')
+      if: (inputs.code_coverage == true) && !contains(inputs.environment, '1ES') && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022') && (steps.skip_check.outputs.should_skip != 'true')
       run: |
         $curlDependencies = Get-Content -Raw "${{github.workspace}}\.github\curl-dependencies.json" | ConvertFrom-Json
         $version = $curlDependencies.opencppcoverage.version
@@ -176,7 +181,7 @@ jobs:
         New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps" -Name "DumpFolder" -Value "$dump_path" -PropertyType ExpandString -ErrorAction SilentlyContinue
 
     - name: Remove existing artifacts
-      if: (inputs.environment == 'ebpf_cicd_tests_ws2019' || inputs.environment == 'ebpf_cicd_tests_ws2022' || inputs.environment == 'ebpf_cicd_perf_ws2022') && (steps.skip_check.outputs.should_skip != 'true')
+      if: (contains(inputs.environment, 'ebpf_cicd') || contains(inputs.environment, '1ES')) && (steps.skip_check.outputs.should_skip != 'true')
       run: |
         Remove-Item -Path ${{github.workspace}}\${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}} -Recurse -Force -ErrorAction SilentlyContinue
 
@@ -221,11 +226,18 @@ jobs:
         .\netevent_ebpf_ext_export_program_info.exe
 
     - name: Run pre test command
-      if: steps.skip_check.outputs.should_skip != 'true' && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022')
+      if: steps.skip_check.outputs.should_skip != 'true' && !contains(inputs.environment, '1ES') && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022')
       id: run_pre_test_command
       working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
       run: |
         ${{env.PRE_COMMAND}}
+
+    - name: Run pre test command on 1ES runner
+      if: steps.skip_check.outputs.should_skip != 'true' && contains(inputs.environment, '1ES')
+      id: run_pre_test_command_1es
+      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+      run: |
+        ${{env.PRE_COMMAND}} -LogFileName ${{ runner.name }}.log -SelfHostedRunnerName '1ESRunner' -RegressionArtifactsConfiguration ${{env.BUILD_CONFIGURATION}}
 
     - name: Run test with Code Coverage and low resource simulation
       if: (inputs.code_coverage == true) && (inputs.fault_injection == true) && (steps.skip_check.outputs.should_skip != 'true')
@@ -253,7 +265,7 @@ jobs:
           OpenCppCoverage.exe -q --sources %CD% --excluded_sources %CD%\external\Catch2 --export_type cobertura:ebpf_for_windows.xml --working_dir ${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}} -- powershell .\Run-Test.ps1 ${{env.DUMP_PATH}} ${{env.TEST_TIMEOUT}} ${{env.TEST_COMMAND}}
 
     - name: Run test without codecoverage
-      if: (inputs.code_coverage != true) && (inputs.vs_dev != true) && (inputs.fault_injection != true) && (steps.skip_check.outputs.should_skip != 'true')
+      if: (inputs.code_coverage != true) && (inputs.vs_dev != true) && (inputs.fault_injection != true) && !contains(inputs.environment, '1ES') && (steps.skip_check.outputs.should_skip != 'true')
       working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
       id: run_test_without_code_coverage
       shell: cmd
@@ -261,13 +273,27 @@ jobs:
           set EBPF_ENABLE_WER_REPORT=yes
           ${{env.TEST_COMMAND}}
 
+    - name: Run test on 1ES runner
+      if: (inputs.code_coverage == false) && (steps.skip_check.outputs.should_skip != 'true') && contains(inputs.environment, '1ES') && (inputs.fault_injection != true)
+      id: run_test_1es
+      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+      run: |
+        ${{env.TEST_COMMAND}} -LogFileName ${{ runner.name }}.log -SelfHostedRunnerName '1ESRunner' -TestJobTimeout ${{env.TEST_TIMEOUT}}
+
     - name: Run post test command
       # Run the post test command even if the workflow has failed.
-      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022')
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && !contains(inputs.environment, '1ES') && (inputs.environment != 'ebpf_cicd_tests_ws2019' && inputs.environment != 'ebpf_cicd_tests_ws2022' && inputs.environment != 'ebpf_cicd_perf_ws2022')
       id: run_post_test_command
       working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
       run: |
         ${{env.POST_COMMAND}}
+
+    - name: Run post test command on 1ES runner
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true') && contains(inputs.environment, '1ES')
+      id: run_post_test_command_1es
+      working-directory: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
+      run: |
+        ${{env.POST_COMMAND}} -LogFileName ${{ runner.name }}.log -SelfHostedRunnerName '1ESRunner'
 
     - name: Check for CodeCoverage
       if: steps.skip_check.outputs.should_skip != 'true'
@@ -335,10 +361,10 @@ jobs:
     - name: Fail if code coverage upload fails
       if: (steps.skip_check.outputs.should_skip != 'true')
       run: |
-        if ($${{ steps.test.upload_code_coverage_report_1!='failure' }}) { exit 0 }
-        if ($${{ steps.test.upload_code_coverage_report_2!='failure' }}) { exit 0 }
-        if ($${{ steps.test.upload_code_coverage_report_3!='failure' }}) { exit 0 }
-        if ($${{ steps.test.upload_code_coverage_report_4!='failure' }}) { exit 0 }
+        if ($${{ steps.upload_code_coverage_report_1.outcome != 'failure' }}) { exit 0 }
+        if ($${{ steps.upload_code_coverage_report_2.outcome != 'failure' }}) { exit 0 }
+        if ($${{ steps.upload_code_coverage_report_3.outcome != 'failure' }}) { exit 0 }
+        if ($${{ steps.upload_code_coverage_report_4.outcome != 'failure' }}) { exit 0 }
         exit 1
 
     - name: Stop ETW tracing
@@ -384,6 +410,14 @@ jobs:
         name: Test-Logs-${{env.NAME}}-${{env.BUILD_PLATFORM}}-${{env.BUILD_CONFIGURATION}}
         path: ./${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}/TestLogs
         retention-days: 5
+
+    - name: Check for generated artifacts
+      # Check for artifacts even if the workflow failed.
+      if: (success() || failure()) && (steps.skip_check.outputs.should_skip != 'true')
+      uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029
+      id: check_artifacts
+      with:
+        files: ${{github.workspace}}\${{env.BUILD_PLATFORM}}\${{env.BUILD_CONFIGURATION}}\Artifacts\*
 
     - name: Upload generated artifacts
       # Upload artifacts even if the workflow failed.
